### ISSUE TITLE
MSSQL Meta Programming

### ISSUE THREAD

**Issue by Heinzad** [Heinzad/data-mache#11]
As a developer, I want to generate database objects from metadata, so that I can automate schema development. 

Given an object name and type, and a ddl operation, when I check the information schema, then I should see that an object of that name and type has been created, altered or deleted. 

Definition of terms used: 
-- Metaprogramming is the process of using programming code to generate or modify further programs. In this case, the scope is within a Microsoft SQL Server (MSSQL) database using the Transact-SQL (T-SQL) dialect. 
-- Data Definition Language, or DDL, defines a schema and the objects in it. 

- [ ] https://github.com/Heinzad/data-mache/issues/12 
- [ ] https://github.com/Heinzad/data-mache/issues/18 
- [ ] https://github.com/Heinzad/data-mache/issues/19
