### ISSUE TITLE
MSSQL Meta Programming Table Generation

### ISSUE THREAD

**Issue by Heinzad** [Heinzad/data-mache#12]
As a developer, I want to access auto-generated DDL, so that I never manually generate scripts myself. 

Given a table name and some column details in the same pattern as the information schema, when I run a procedure then I should see its details in the information schema tables. 

Definitions: 
- Data Definition Language (DDL) is used to create, alter or delete objects. 
- Metaprogramming uses code to generate other code.

Tasks: 
 
- [ ] https://github.com/Heinzad/data-mache/issues/13 
- [ ] https://github.com/Heinzad/data-mache/issues/14 
- [ ] https://github.com/Heinzad/data-mache/issues/15
