### ISSUE TITLE
MSSQL Meta Programming Testing

### ISSUE THREAD

**Issue by Heinzad** [Heinzad/data-mache#20]
- As a developer, I want to access some routine tests, so that I don't have to rewrite them every time. 

- Given an object name, when I run the test, I should discover if the object exists. 

- [ ] [Database Exists](https://github.com/Heinzad/data-mache/issues/21)
- [ ] [Schema Exists](https://github.com/Heinzad/data-mache/issues/22) 
- [ ] [Table Exists](https://github.com/Heinzad/data-mache/issues/23)
- [ ] [Column Exists](https://github.com/Heinzad/data-mache/issues/24) 
- [ ] [Column Property Exists](https://github.com/Heinzad/data-mache/issues/25)
